apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-devops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-devops-app
  template:
    metadata:
      labels:
        app: complete-devops-app
    spec:
      containers:
      - name: complete-devops-app
        image: abhigyanbasu/complete-prodcution-e2e-pipeline:1.0.0-15
        resources:
         limits:
          memory: "256Mi"
          cpu: "500m"
        ports:
        - containerPort: 8080
